[package]
name = "uwumail-dav"
description = "CalDAV and CardDAV for the UwUMail server"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
uwumail-jmap.workspace = true
uwumail-smtp.workspace = true
uwumail-store.workspace = true

axum.workspace = true
base64.workspace = true
bytes.workspace = true
http-body-util.workspace = true
hyper-rustls.workspace = true
hyper-util.workspace = true
psl.workspace = true
quick-xml.workspace = true
rustls.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
url.workspace = true
webpki-roots.workspace = true

[dev-dependencies]
tempfile.workspace = true
tower.workspace = true
